# pdsite configuration

theme: default
inputextension: .md
outputfolder: .html

# Site-wide template variables

sitename: "Gord's Notebook"
footer: '<span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Text" rel="dct:type">Site contents</span> by <a class="navbar-link" xmlns:cc="http://creativecommons.org/ns#" href="http://notes.gordstephen.ca" property="cc:attributionName" rel="cc:attributionURL">Gord Stephen</a> licensed under <a class="navbar-link" rel="license" href="http://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>'
bootswatch: cosmo 
